baseURL = "https://maopitz.github.io/"
languageCode = "en-us"
title = "Masonâ€™s ASE230 Portfolio"
theme = "hugo-book"
publishDir = "docs"

[params]
  BookTheme = "auto"
  BookToC = true
  BookSection = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
